.TH fancy 3 "2/10/2000" " " "PETSc"
.SH NAME
fancy \-  Shows all fancy formatting 
.SH SYNOPSIS
.nf
#include <sys/time.h> 
#include <sys/types.h> 
void f1( int a, char *b )
.fi
.SH INPUT PARAMETERS
.PD 0
.TP
.B x, y 
- Coords
.PD 1
.PD 0
.TP
.B a 
- the `really` important value
.PD 1

.SH OUTPUT PARAMETERS
.PD 0
.TP
.B p1 
- pointer `to a`. Is this here?
.PD 1

.SH NOTES
This system uses the line
.br
break mechanism
.br

as well as
.nf
a     verbatim
table example
.fi

and a line ending in colon:

.RS
This is in quotation format
.RE


.SH NOTES ON FNODES
This is a sample that includes
.nf
verbatim 
processing
.fi


.SH KEYWORDS
break, pointers
.br
.SH LOCATION
allfmt.c
