.TH foobartable 3 "2/10/2000" " " "PETSc"
.SH NAME
foobartable \-  Foo bar test 
.SH SYNOPSIS
.nf
void foobartable(int a)
.fi
.SH INPUT PARAMETERS
.PD 0
.TP
.B -arg 1 
- foo is foo
.PD 1
.PD 0
.TP
.B n, m 
- fish is fish
.PD 1
.PD 0
.TP
.B j 
- No one here is entirely who they appear to be
.PD 1
.PD 0
.TP
.B g'kar 
- said that, the rest of this line is a long bit of text to see how 
the table code handles text that won't fit on a single line of text.
.PD 1

.SH LOCATION
tst1.c
