.TH mystruct 3 "2/10/2000" " " "PETSc"
.SH NAME
mystruct \-  structure of pointers 
.SH SYNOPSIS
.nf
int *pointer;
int n;
for (i=0; i<n; i++) { pointer_array[i] = area to fill; }
This line tests special characters: $, |, \\, &, <>, 't', "text"
.fi
This is the end, and is `not` part of the synopsis.
.SH LOCATION
tststra.h
