.TH Tst2_start 2 "2/10/2000" " " "MTEST"
.SH NAME
Tst2_start \-  Sample C only routine 
.SH SYNOPSIS
.nf
#include "tools.h"
#include "system/system.h"
void Tst2_start( a, b )
int a, b;
.fi
This example uses
.br
   The $ symbol to do verbatim output
.br
   up to here

.RS
Caption for figure
.RE



.SH LOCATION
tstpgmc.c
