#! /bin/sh
#
# Make a tar file of the SOWING code, removing the RCS files etc.
#
TMPDIR=/sandbox/gropp
do_install="no"
notar="no"
for arg in "$@" ; do
    case $arg in 
    -install) do_install="yes"
    ;;
    -notar) notar="yes"
    ;;
    *) echo "Unrecognized argument $arg"
       exit 1
       ;;
    esac
done

echo "If you are making a distribution version, update src/doctext/doc.h"
echo "and include/patchlevel.h.in for version number and date."

#
# Generate version number for file name
m1=`grep 'PATCHLEVEL ' include/patchlevel.h.in | awk '{print $3}'`
m2=`grep 'PATCHLEVEL_MINOR ' include/patchlevel.h.in | awk '{print $3}'`
m3=`grep 'PATCHLEVEL_SUBMINOR ' include/patchlevel.h.in | awk '{print $3}'`
Version="$m1.$m2.$m3"
#
set -x
#
# Use tar to copy to $TMPDIR
if [ -d $TMPDIR/sowingcopy ] ; then
    /bin/rm -rf $TMPDIR/sowingcopy/sowing
else
    mkdir $TMPDIR/sowingcopy
fi
cd $TMPDIR/sowingcopy
tar cf - -C /homes/gropp/sowing-proj sowing | tar xf -
#
# Update a few files
#
rm $TMPDIR/sowingcopy/sowing/tarch
cp /home/MPI/mpich/util/tarch $TMPDIR/sowingcopy/sowing
#
# Remove the RCS files, old executables, and debris
cd $TMPDIR/sowingcopy/sowing
if [ -s Makefile ] ; then
    make distclean
fi
# The sed for ' win32' to '\\ win32' handles blanks in the filenames
find $TMPDIR/sowingcopy/sowing \( -name 'RCS' -o -name '*.o' -o -name '#*#' -o \
              -name '*~' -o -name 'mputil.mp*' -o -name Makefile -o \
	      -name makefile -o -name '*.exe' -o -name core -o \
	      -name '*.obj' -o -name '*.pdb' -o -name '*.lib' -o \
	      -name '*.ilk' -o -name '*.pch' -o -name 'CVS' \) -print | \
	sed -e 's/ win32/\\ win32/g' | sed 's%^%/bin/rm -rf %g' | sh
# Remove some directories
/bin/rm -rf  $TMPDIR/sowingcopy/sowing/related
/bin/rm -rf  $TMPDIR/sowingcopy/sowing/maint
/bin/rm -rf  $TMPDIR/sowingcopy/sowing/docs/coding
/bin/rm -rf  $TMPDIR/sowingcopy/sowing/notes
/bin/rm -rf  $TMPDIR/sowingcopy/sowing/ToDo
/bin/rm -f   $TMPDIR/sowingcopy/sowing/bin/doctext
#
# Remove the configure-generated files
/bin/rm -f $TMPDIR/sowingcopy/sowing/tohtml/tohtmlpath.h
/bin/rm -f $TMPDIR/sowingcopy/sowing/bin/pstoxbm
/bin/rm -f $TMPDIR/sowingcopy/sowing/bin/pstogif
/bin/rm -f $TMPDIR/sowingcopy/sowing/doctext/docpath.h
/bin/rm -f $TMPDIR/sowingcopy/sowing/include/textfilt/textpath.h
/bin/rm -f $TMPDIR/sowingcopy/sowing/include/patchlevel.h
/bin/rm -f $TMPDIR/sowingcopy/sowing/include/sowingconfig.h
#
/bin/rm -f $TMPDIR/sowingcopy/sowing/make.log
/bin/rm -f $TMPDIR/sowingcopy/sowing/docs/*.log
/bin/rm -f $TMPDIR/sowingcopy/sowing/docs/*.hux
/bin/rm -f $TMPDIR/sowingcopy/sowing/src/findlibs

if [ $notar = "yes" ] ; then exit 0 ; fi
#
# rebuild the tar file
cd $TMPDIR/sowingcopy
#
# Rename the directory
mv $TMPDIR/sowingcopy/sowing $TMPDIR/sowingcopy/sowing-$Version
tar cf - sowing-$Version | gzip > $TMPDIR/sowing-$Version.tar.gz
if [ $do_install = "yes" ] ; then
    cp $TMPDIR/sowing-$Version.tar.gz /home/ftp/pub/sowing
    echo "sowing-$Version.tar.gz is in ftp:pub/sowing"
else
    cp $TMPDIR/sowing-$Version.tar.gz $HOME/sowing-proj
fi
#
# Remove the copy
cd $TMPDIR
/bin/rm -rf $TMPDIR/sowingcopy $TMPDIR/sowing-$Version.tar.gz &

